#!/bin/bash

function close() {
	eww -c "$HOME/.config/eww/fool_moon/menu" close sys-menu time-menu
	$HOME/.scripts/dashboard close
}

function lock() {
	close
  mpc -p 6600 pause &
	betterlockscreen -l blur
}

function llogout() {
	close
	bspc quit
}

function rrestart() {
	close
	reboot
}

function sshutdown() {
	close
	shutdown now
}

case "$1" in
	lock) lock;;
	logout) llogout;;
	reboot) rrestart;;
	shutdown) sshutdown;;
	*) echo "unrecognized command" && exit 1;;
esac

