#!/bin/sh

bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
        if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
            #echo "1"
            bspc monitor $(bspc query -M | sed -n 1p) -d 1 4 7 8 9
            bspc monitor $(bspc query -M | sed -n 2p) -d 2 5
            bspc monitor $(bspc query -M | sed -n 3p) -d 3 6
        elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
            bspc monitor $(bspc query -M | sed -n 2p) -d 1 3 5 6 7 8 9
            bspc monitor $(bspc query -M | sed -n 1p) -d 2 4
        else
            bspc monitor -d 1 2 3 4 5 6 7 8 9
        fi
        ;;
      *)
      ;;
  esac
done &

