#!/bin/sh
# reset bspc rules when first running
bcpc rule -r "*"

# get node property:
# first get the id:
# xdotool search --name "<program name>"
# or --class "<program class>"
# bspc node <id> --focus;bspc query -T -n

#$HOME/.scripts/autostart.sh
##############################################################

### Monitors ###
bspc monitor eDP1 -d 1 3 5 6 7 8 9
bspc monitor DP1 -d 2 4
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

### Global Settings ###
xsetroot -cursor_name ptr &

# Windows and borders
bspc config border_width            0
bspc config window_gap              10
bspc config top_padding             22
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

# Layouts
# how bigger will the master window be 
# compared to the slaves side by side
# 0.50 is same size, 0.52 is 0.2 times bigger and etc
bspc config split_ratio             0.50

# monocle
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config top_monocle_padding     6
bspc config right_monocle_padding   0
bspc config bottom_monocle_padding  0           
bspc config left_monocle_padding    0
# if there's only 1 window in the tree, set it to monocle
bspc config single_monocle          true

# Mouse
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner
bspc config focus_follows_pointer   true
bspc config click_to_focus          none
bspc config swallow_first_click     true

# Colors
bspc config normal_border_color     "#000000"
bspc config active_border_color     "#7fadff"
bspc config focused_border_color    "#7fadff"
bspc config presel_border_color     "#7fadff"
bspc config urgent_border_color     "#7fadff"

### Rules ###
# exec stuff in the autostart.sh
# so that it wont duplicate everytime
# the config file is reset
#sleep 3 && urxvt -name floating_terminal &
bspc rule -a "*:*:floating_terminal" hidden=on sticky=on state=floating rectangle=570x360+400+32 
#sleep 3 && urxvt -name floating_terminal2 &
bspc rule -a "*:*:floating_terminal2" hidden=on sticky=on state=floating rectangle=1356x732+3+28
#sleep 3 && spotify &
# spotify (or bspwm) is bugged, it shows as having no class/name
#bspc rule -a "*:" hidden=on sticky=on state=floating rectangle=800x600+283+84
#sleep 3 && firefox &
bspc rule -a firefox hidden=on sticky=on state=floating rectangle=1356x732+3+28
#sleep 3 && discord &
#premid &
bspc rule -a discord hidden=on sticky=on state=floating rectangle=1356x732+3+28
bspc rule -a Arandr state=floating
bspc rule -a Pavucontrol state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
