#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

# use these if needed
#class=$(echo ${2} | xargs)
#instance=$(echo ${3} | xargs)

case $class in
    "URxvt" | "St")
        if [ "$title" = "floating_terminal" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=570x360+400+32"
        fi
        if [ "$title" = "floating_terminal2" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1356x732+3+28"
        fi
        if [ "$title" = "ncmpcpp" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=801x525+275+100"
        fi
       ;;
    "firefox")
        if [[ "$title" = "Save File" || "$title" = "Save As" ]]; then
            echo "state=floating"
            echo "rectangle=723x543+1687+103"
        elif [[ "$title" = "File Upload" ]]; then
            echo "state=floating"
            echo "rectangle=723x543+1687+103"
        else
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1356x732+3+28"
        fi
        ;;
    "Google-chrome")
        if [[ $instance == crx* ]]; then
            echo "state=floating"
            echo "center=on"
        else
            echo "rectangle=1342x732+1376+16"
        fi
        ;;
    "discord" | "lightcord")
        if [[ "$title" =~ .*\Discord ]]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1356x732+3+28"
        fi
        if [[ "$title" =~ .*\Lightcord ]]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1356x732+3+28"
        fi
        ;;
    "XTerm" | "UXTerm")
        echo "state=floating"
        echo "rectangle=872x501+1613+127"
        ;;
    "Minecraft Launcher" | "minecraft-launcher")
        echo "state=floating"
        echo "rectangle=999x658+1547+55"
        ;;
    "lunarclient")
        echo "state=floating"
        echo "rectangle=973x666+1559+50"
        ;;
    "Pavucontrol")
        echo "state=floating"
        echo "rectangle=703x451+1695+156"
        ;;
    "Nitrogen")
        echo "state=floating"
        echo "rectangle=553x627+1780+68"
        ;;
    "qutebrowser")
        echo "state=floating"
        echo "center=on"
        ;;
    "realvnc-vncviewer")
        echo "state=floating"
        echo "rectangle=870x546+113+221"
        echo "center=on"
        #if [[ "$title | awk '/) - VNC Viewer/{print}'" ]]; then
        #    echo "state=floating"
        #    echo "rectangle=1356x732+3+28"
        #fi
        ;;
    "realvnc-vncserverui-service")
        echo "state=floating"
        echo "center=on"
        ;;
    "Manjaro Settings Manager")
        echo "state=floating"
        ;;
    "Arandr")
        echo "state=floating"
        ;;
    "kcalc")
        echo "state=floating"
        ;;
    "copyq")
        echo "state=floating"
        echo "rectangle=645x395+1724+184"
        #echo "hidden=on"
        #echo "sticky=on"
        #echo "center=on"
        #echo "focus=on"
        ##echo "follow=on"
        ##echo "desktop=focused"
        ##echo "monitor=focused"
        #if [[ "$title" = "Preferences — CopyQ" ]]; then
        #    echo "state=floating"
        #    echo "hidden=off"
        #fi
        # bspc node <copyq wid> --to-<monitor|desktop> focused --focus
        ;;
    "Lxappearance")
        echo "state=floating"
        ;;
    "Pamac-manager")
        echo "state=floating"
        ;;
    "MEGAsync")
        echo "state=floating"
        ;;
    "GParted")
        echo "state=floating"
        ;;
    "Kvantum Manager")
        echo "state=floating"
        ;;
    "Gucharmap")
        echo "state=floating"
        ;;
    "Soundux")
        echo "state=floating"
        ;;
    "Xfce4-mime-settings")
        echo "state=floating"
        ;;
    "qt5ct" | "qt6ct")
        echo "state=floating"
        ;;
    "SimpleScreenRecorder")
        echo "state=floating"
        ;;
    "scrcpy")
        echo "state=floating"
        echo "rectangle=402x715+486+36"
        ;;
    "Steam" | "steam")
        if [[ $title =~ "Properties".* ]]; then
            echo "state=floating"
        else
            echo "state=floating"
            echo "rectangle=1314x701+1388+23"
        fi
        ;;
    "Spotify")
        echo "state=floating"
        echo "rectangle=963x682+1559+49"
        ;;
    "GameConqueror.py")
        echo "state=floating"
        ;;
esac

case $title in
    "Java" | "Burp Suite Community Edition"* )
        if [[ $title =~ .*"Temporary Project" ]]; then
            echo "center=on"
        else
            echo "state=floating"
            echo "center=on"
        fi
        ;;
    "Task Manager - Google Chrome")
        echo "state=floating"
        echo "rectangle=923x543+1590+103"
        #echo "center=on"
        ;;
    "Bitwarden")
        echo "state=floating"
        ;;
    "Save File")
        echo "state=floating"
        echo "rectangle=723x543+1687+103"
        ;;
    "Open File" | "Open Files")
        echo "state=floating"
        echo "rectangle=723x543+1687+103"
        ;;
    "Power Manager")
        echo "state=floating"
        ;;
    "Network Connections")
        echo "state=floating"
        ;;
esac


