#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

# use these if needed
#class=$(echo ${2} | xargs)
#instance=$(echo ${3} | xargs)

# xprop
# WM_CLASS(STRING) = instance, class
# WM_NAME(STRING) = title

case $class in
    "URxvt" | "St")
        if [ "$title" = "floating_terminal" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=722x477+1974+62"
        fi
        if [ "$title" = "floating_terminal2" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            #echo "rectangle=1356x732+3+28"
            echo "rectangle=1346x717+1653+199"
            # echo "center=on"
        fi
        if [ "$title" = "ncmpcpp" ]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=801x525+275+100"
            echo "center=on"
        fi
       ;;
    "firefox")
        if [[ "$title" = "Save File" || "$title" = "Save As" ]]; then
            echo "state=floating"
            echo "rectangle=723x543+1687+103"
            echo "center=on"
        elif [[ "$title" = "File Upload" ]]; then
            echo "state=floating"
            echo "rectangle=723x543+1687+103"
            echo "center=on"
        else
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1356x732+3+28"
            echo "center=on"

        fi
        ;;
    "Google-chrome")
        if [[ $instance == crx* ]]; then
            echo "state=floating"
            echo "center=on"
        else
            echo "rectangle=1342x732+1376+16"
            echo "center=on"

        fi
        ;;
    "discord" | "lightcord")
        if [[ "$title" =~ .*\Discord ]] || [[ "$title" =~ .*\Lightcord ]]; then
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            echo "rectangle=1357x724+3+28"
            echo "center=on"
        fi
        ;;
    "XTerm" | "UXTerm")
        echo "state=floating"
        echo "rectangle=872x501+1613+127"
        echo "center=on"
        ;;
    "Minecraft Launcher" | "minecraft-launcher")
        echo "state=floating"
        echo "rectangle=999x658+1547+55"
        echo "center=on"
        ;;
    "lunarclient")
        echo "state=floating"
        echo "rectangle=973x666+1559+50"
        ;;
    "Pavucontrol")
        echo "state=floating"
        echo "rectangle=703x451+1695+156"
        echo "center=on"
        ;;
    "Nitrogen")
        echo "state=floating"
        echo "rectangle=553x627+1780+68"
        echo "center=on"
        ;;
    "qutebrowser")
        echo "state=floating"
        echo "center=on"
        ;;
    "Archlinux-tweak-tool.py")
        echo "state=floating"
        echo "center=on"
        ;;
    "realvnc-vncviewer")
        echo "state=floating"
        echo "rectangle=870x546+113+221"
        echo "center=on"
        #if [[ "$title | awk '/) - VNC Viewer/{print}'" ]]; then
        #    echo "state=floating"
        #    echo "rectangle=1356x732+3+28"
        #fi
        ;;
    "realvnc-vncserverui-service")
        echo "state=floating"
        echo "center=on"
        ;;
    "Manjaro Settings Manager")
        echo "state=floating"
        echo "center=on"
        ;;
    "Arandr")
        echo "state=floating"
        echo "center=on"
        ;;
    "kcalc")
        echo "state=floating"
        echo "center=on"
        ;;
    "copyq")
        echo "state=floating"
        # echo "rectangle=645x395+1724+184"
        echo "rectangle=800x426+275+312"
        echo "center=on"
        #echo "hidden=on"
        #echo "sticky=on"
        #echo "focus=on"
        ##echo "follow=on"
        ##echo "desktop=focused"
        ##echo "monitor=focused"
        #if [[ "$title" = "Preferences — CopyQ" ]]; then
        #    echo "state=floating"
        #    echo "hidden=off"
        #fi
        # bspc node <copyq wid> --to-<monitor|desktop> focused --focus
        ;;
    "Lxappearance")
        echo "state=floating"
        echo "center=on"
        ;;
    "Pamac-manager")
        echo "state=floating"
        echo "center=on"
        ;;
    "MEGAsync")
        echo "state=floating"
        ;;
    "GParted")
        echo "state=floating"
        ;;
    "Kvantum Manager")
        echo "state=floating"
        ;;
    "Gucharmap")
        echo "state=floating"
        ;;
    "Soundux")
        echo "state=floating"
        ;;
    "Cpupower-gui")
        echo "state=floating"
        ;;
    "yad-calendar")
        echo "state=floating"
        ;;
    "Xfce4-mime-settings")
        echo "state=floating"
        ;;
    "qt5ct" | "qt6ct")
        echo "state=floating"
        ;;
    "SimpleScreenRecorder")
        echo "state=floating"
        ;;
    "Xfce4-appearance-settings")
        echo "state=floating"
        echo "rectangle=580x596+1761+77"
        ;;
    "scrcpy")
        echo "state=floating"
        # echo "rectangle=402x715+486+36"
        ;;
    "Steam" | "steam")
        if [[ $title =~ "Properties".* ]]; then
            echo "state=floating"
        else
            echo "state=floating"
            echo "rectangle=1314x701+1388+23"
            echo "center=on"
        fi
        ;;
    "TelegramDesktop")
        echo "state=floating"
        echo "rectangle=1314x714+1389+36"
        echo "center=on"
        ;;
    "GameConqueror.py")
        echo "state=floating"
        ;;
    "qBittorrent")
        echo "desktop=2"
        ;;
    "Nvidia-settings")
        echo "state=floating"
        ;;
    "Gwe")
        echo "state=floating"
        ;;
    # For programs that takes too long to set a WM_CLASS
    *)
        case $(ps -p "$(xdo pid "$wid")" -o comm= 2>/dev/null) in
        spotify)
            echo "state=floating"
            echo "hidden=on"
            echo "sticky=on"
            # echo "rectangle=963x682+1559+49"
            echo "rectangle=1020x678+171+180"
            echo "center=on"
        ;;
        esac
    ;;
esac

case $title in
    # "Java" | "Burp Suite Community Edition"* )
    #     if [[ $title =~ .*"Temporary Project" ]]; then
    #         echo "state=floating"
    #         echo "center=on"
    #     else
    #         echo "state=floating"
    #         echo "center=on"
    #     fi
    #     ;;
    "Task Manager - Google Chrome")
        echo "state=floating"
        echo "rectangle=923x543+1590+103"
        echo "center=on"
        ;;
    "Bitwarden")
        echo "state=floating"
        ;;
    "Save File")
        echo "state=floating"
        echo "rectangle=723x543+1687+103"
        ;;
    "Open File" | "Open Files")
        echo "state=floating"
        echo "rectangle=723x543+1687+103"
        ;;
    "Power Manager")
        echo "state=floating"
        ;;
    "Network Connections")
        echo "state=floating"
        ;;
esac



