#!/bin/sh

power=$(acpi -a | awk '{print $3}')

if [[ $power = "on-line" ]]; then
  echo "Connected to power, setting CPU governor to Ondemand"
  cpupower-gui profile Ondemand >/dev/null
  # cpupower-gui profile Performance >/dev/null

  # echo "ondemand" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  # sudo cpupower frequency-set -g ondemand
  #echo "1" | sudo tee /sys/devices/system/cpu/cpufreq/boost
else
  echo "Not connected to power, setting CPU governor to powersave"
  cpupower-gui profile Powersave >/dev/null

  # echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  # sudo cpupower frequency-set -g powersave
  #echo "0" | sudo tee /sys/devices/system/cpu/cpufreq/boost
fi

