#!/bin/sh

power=$(acpi -a | awk '{print $3}')

if [[ $power = "on-line" ]]; then
  echo "Connected to power, setting CPU Boost on"
  sudo cpupower frequency-set -g ondemand
  echo "1" | sudo tee /sys/devices/system/cpu/cpufreq/boost
else
  echo "Not connected to power, setting CPU Boost off"
  sudo cpupower frequency-set -g powersave
  echo "0" | sudo tee /sys/devices/system/cpu/cpufreq/boost
fi

