#!/bin/sh

# May crash chrome

file=/tmp/gamemode
notifyid=6125

# if there's not gamemode file in /tmp/
if [ -z $(ls /tmp/gamemode) ]; then
    # Create toggle file
    touch $file

    # Send notify 
    dunstify -t 1500 -i "/usr/share/icons/Papirus-Dark/22x22/actions/attentions.svg" "Enabling Game mode" -r $notifyid

    # now it completely kills chrome
    # Kill chrome GPU process
    #kill $(ps auxf | grep "gpu" | grep "chrome" | awk '{print $2}')
   
    # Killing polybar
    kill -9 $(ps aux | grep polybar | grep main | awk '{print $2}')

    # Enable performance cpu scheduler
    cpupower-gui profile Performance >/dev/null

    # Kill compositor
    sleep 1.6 && killall picom
    
    # Disable notifications
    sleep 0.8 && dunstctl set-paused true

else
    # Re enable notifications
    dunstctl close-all
    dunstctl set-paused false

    # Send notify
    dunstify -t 1500 -i "/usr/share/icons/Papirus-Dark/22x22/actions/attentions.svg" "Disabling Game mode" -r $notifyid

    # Starting Polybar
    $HOME/.config/polybar/launch.sh && sleep 1.2 && bspc config top_padding 33 &

    # Enable performance cpu scheduler
    cpupower-gui profile Conservative >/dev/null

    # Starting compositor
    picom -b &

    # Delete toggle file
    rm $file
fi
